### PR TITLE
resolve a page's information before displaying it

### PR DESCRIPTION
**Pull request by jarischaefer**
Fixes the flickering on page load

### CODE REVIEW

**Comment by tobegit3hub** [comment]
Sorry for the late response. I will test the patch soon and thanks for your contribution @jarischaefer 👍

**Comment by tobegit3hub** [comment]
There're some updates about `golang` and `beego`. Can you rebase from the master brach? The image seems not to be built because of those changes.

**Comment by jarischaefer** [comment]
I updated the branch.

**Comment by tobegit3hub** [comment]
Thanks @jarischaefer and it looks pretty good 👍

**Pull request merged**
