### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by arckosfr**
Replace Golang by Golang:Alpine.
for a weight gain

### CODE REVIEW

**Comment by tobegit3hub** [comment]
Thanks @jarischaefer and I will test this soon.

It seems the version of golang in CI is wrong which breaks the test. Please just ignore it.

**Comment by arckosfr** [comment]
Yep i see it (for CI) thanks for taking a look :+1:

**Comment by tobegit3hub** [comment]
Great! It works like a charm and compress the image from 797.3 MB to 313.9 MB.

Thanks for your contribution @arckosfr and I would like to merge this 😄

**Comment by jarischaefer** [comment]
I guess you did not intend to ping me in this pull request? Mine is still open, though.

**Pull request merged**
